DEATH_STATE: str = 'death_state'
WALK_STATE: str = 'walk_state'
PUNCH_STATE: str = 'punch_state'
AFTER_PUNCH_STATE: str = 'after_punch_state'
INVENTORY_OPEN_STATE: str = 'inventory_open_state'
STEAL_STATE: str = 'steal_state'
SHIELD_STATE: str = 'shield_state'
IDLE_STATE: str = 'idle_state'
