DEATH_STATE = 'death_state'
WALK_STATE = 'walk_state'
PUNCH_STATE = 'punch_state'
AFTER_PUNCH_STATE = 'after_punch_state'
INVENTORY_OPEN_STATE = 'inventory_open_state'
STEAL_STATE = 'steal_state'
SHIELD_STATE = 'shield_state'
IDLE_STATE = 'idle_state'
