import pygame as pg

from Views.Display import Display


DISPLAY_WIDTH = 700
DISPLAY_HEIGHT = 700
DISPLAY_NAME = 'DUNGEON'

DISPLAY = Display(DISPLAY_WIDTH, DISPLAY_HEIGHT, DISPLAY_NAME)
ENTITIES_SURFACE = pg.Surface((DISPLAY_WIDTH, DISPLAY_HEIGHT))
ROOMS_SURFACE = pg.Surface((DISPLAY_WIDTH, DISPLAY_HEIGHT))