from BaseVariables.Saves.SaveFilesPaths import *

from Models.Save import Save

FIRST_AUTO_SAVE = Save(FIRST_AUTO_SAVE_FILE_PATH)
SECOND_AUTO_SAVE = Save(SECOND_AUTO_SAVE_FILE_PATH)
THIRD_AUTO_SAVE = Save(THIRD_AUTO_SAVE_FILE_PATH)
FOURTH_AUTO_SAVE = Save(FOURTH_AUTO_SAVE_FILE_PATH)
FIFTH_AUTO_SAVE = Save(FIFTH_AUTO_SAVE_FILE_PATH)

FIRST_SAVE = Save(FIRST_SAVE_FILE_PATH)
SECOND_SAVE = Save(SECOND_SAVE_FILE_PATH)
THIRD_SAVE = Save(THIRD_SAVE_FILE_PATH)
FOURTH_SAVE = Save(FOURTH_SAVE_FILE_PATH)
FIFTH_SAVE = Save(FIFTH_SAVE_FILE_PATH)

AUTO_SAVES = [FIRST_AUTO_SAVE, SECOND_AUTO_SAVE, THIRD_AUTO_SAVE, FOURTH_AUTO_SAVE, FIFTH_AUTO_SAVE]

SAVES = [FIRST_SAVE, SECOND_SAVE, THIRD_SAVE, FOURTH_SAVE, FIFTH_SAVE]