from BaseVariables.Saves.SaveFilesPaths import *

from Models.Save import Save

FIRST_AUTO_SAVE: Save = Save(FIRST_AUTO_SAVE_FILE_PATH)
SECOND_AUTO_SAVE: Save = Save(SECOND_AUTO_SAVE_FILE_PATH)
THIRD_AUTO_SAVE: Save = Save(THIRD_AUTO_SAVE_FILE_PATH)
FOURTH_AUTO_SAVE: Save = Save(FOURTH_AUTO_SAVE_FILE_PATH)
FIFTH_AUTO_SAVE: Save = Save(FIFTH_AUTO_SAVE_FILE_PATH)

FIRST_SAVE: Save = Save(FIRST_SAVE_FILE_PATH)
SECOND_SAVE: Save = Save(SECOND_SAVE_FILE_PATH)
THIRD_SAVE: Save = Save(THIRD_SAVE_FILE_PATH)
FOURTH_SAVE: Save = Save(FOURTH_SAVE_FILE_PATH)
FIFTH_SAVE: Save = Save(FIFTH_SAVE_FILE_PATH)

AUTO_SAVES: list[Save] = [FIRST_AUTO_SAVE, SECOND_AUTO_SAVE, THIRD_AUTO_SAVE, FOURTH_AUTO_SAVE, FIFTH_AUTO_SAVE]

SAVES: list[Save] = [FIRST_SAVE, SECOND_SAVE, THIRD_SAVE, FOURTH_SAVE, FIFTH_SAVE]